apps/courses/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path

from apps.courses.views import CoursesListView, CoursesDetailView, CoursesCommentsView
from apps.courses.views import CoursesVideosView, CoursesPlayView

app_name = 'apps.courses'
urlpatterns = [
    path('list/', CoursesListView.as_view(), name="list"),
    re_path('detail/(?P<course_id>.*)/', CoursesDetailView.as_view(), name="course_detail"),
    re_path('videos/(?P<course_id>.*)/', CoursesVideosView.as_view(), name="course_videos"),
    re_path('comments/(?P<course_id>.*)/', CoursesCommentsView.as_view(), name="course_comments"),
    re_path('play/(?P<video_id>.*)/', CoursesPlayView.as_view(), name="course_play"),
]

apps/operation/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from apps.operation.views import AddUserAskView, AddUserFavouriteView, AddCommentsView, DeleteCommentsView

app_name = 'apps.operation'
urlpatterns = [
    path('add_ask/', AddUserAskView.as_view(), name="add_ask"),
    path('add_fav/', AddUserFavouriteView.as_view(), name="add_fav"),
    path('add_comments/', AddCommentsView.as_view(), name='add_comments'),
    path('del_comments/', DeleteCommentsView.as_view(), name='del_comments'),
]

apps/organization/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path

from apps.organization.views import OrganizationCoursesView, OrganizationDescirbeView
from apps.organization.views import OrganizationTeacherView, TeacherListView, TeacherInfoView
from apps.organization.views import OrganizationView, OrganizationHomeView

app_name = 'apps.organization'
urlpatterns = [
    path('list/', OrganizationView.as_view(), name="list"),
    path('teachers_list/', TeacherListView.as_view(), name="list_teachers"),
    re_path('home/(?P<org_id>.*)/', OrganizationHomeView.as_view(), name="home"),
    re_path('courses/(?P<org_id>.*)/', OrganizationCoursesView.as_view(), name="courses"),
    re_path('desc/(?P<org_id>.*)/', OrganizationDescirbeView.as_view(), name="desc"),
    re_path('teachers/(?P<org_id>.*)/', OrganizationTeacherView.as_view(), name="teachers"),
    re_path('teachers_info/(?P<teacher_id>.*)/', TeacherInfoView.as_view(), name="teachers_info"),
]

apps/users/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path

from apps.users.views import ActiveUserView, LoginView, LogoutView, RegisterView, ForgetPasswordView, ResetPasswordView
from apps.users.views import MyCoursesView, MyFavouriteView, MyMessagesView, MyMessagesContentView
from apps.users.views import UserInfoView, UploadImageView, ResetPasswordInfoView, UpdateEmailView

app_name = 'apps.users'
urlpatterns = [
    # 登录/注销
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # 注册
    path('register/', RegisterView.as_view(), name="register"),
    re_path('active/(?P<verify_code>.*)/', ActiveUserView.as_view(), name="user_acitve"),
    # 找回密码
    path('forgetpwd/', ForgetPasswordView.as_view(), name="find_password"),
    re_path('forget/(?P<verify_code>.*)/', ResetPasswordView.as_view(), name="reset_password"),

    # 用户个人信息界面/保存修改信息
    path('info/', UserInfoView.as_view(), name="user_info"),
    # 用户修改密码
    path('resetpwd/', ResetPasswordInfoView.as_view(), name='reset_info_password'),
    # 用户修改邮箱
    path('update_email/', UpdateEmailView.as_view(), name='update_email'),
    # 用户上传头像
    path('upload_image/', UploadImageView.as_view(), name='upload_image'),

    # 用户学习课程
    path('mycourses/', MyCoursesView.as_view(), name='my_courses'),
    # 用户收藏
    re_path('myfav/(?P<types>.*)/', MyFavouriteView.as_view(), name="my_favourite"),
    # 用户消息
    path('messages/', MyMessagesView.as_view(), name='my_messages'),
    # 消息内容
    re_path('content/(?P<msg_id>.*)/', MyMessagesContentView.as_view(), name="msg_content"),
]

mooc_example/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

import mooc_example.exception
from apps.users.views import IndexView
from mooc_example.settings import MEDIA_ROOT, STATIC_ROOT

urlpatterns = [
    # 后台管理
    path('admin/', admin.site.urls),

    # 主页
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # 用户登录
    path('users/', include('apps.users.urls', namespace='users')),

    # 用户操作
    path('operation/', include('apps.operation.urls', namespace='operations')),

    # 课程机构
    path('orgs/', include('apps.organization.urls', namespace='orgs')),

    # 公开课
    path('courses/', include('apps.courses.urls', namespace='courses')),

    # 验证码
    path('captcha/', include('captcha.urls')),

    # 上传图片
    re_path('^upload/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    # 静态文件
    re_path('^static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
]

# 全局错误页面
handler403 = mooc_example.exception.page_permission_denied
handler404 = mooc_example.exception.page_not_found
handler500 = mooc_example.exception.page_error

templates/base-content.html
<!DOCTYPE html>
<html lang="zh">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <!-- block模块可以被继承修改 -->
    <title>{% block title %}标题{% endblock %}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block external %}
    {% endblock %}
    {% block js %}
        <script>
            var course_list_url = "{% url 'courses:list' %}";
            var org_list_url = "{% url 'orgs:list' %}";
            var teachers_list_url = "{% url 'orgs:list_teachers' %}";
        </script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
        <script src="{% static 'js/selectUi.js' %}"></script>
        <script src="{% static 'js/deco-common.js' %}"></script>
        <script src="{% static 'js/unslider.js' %}"></script>
        <script src="{% static 'js/index.js' %}"></script>
        <script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
        <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
        <script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
        <script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>
    {% endblock %}
</head>

<body>
    <section class="headerwrap">
        <header>
            <div class="header">
                <!-- 顶部水平栏 -->
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>123456789</b></p></div>
                        <!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                            <div class="personal">
                                <dl class="user fr">
                                    <dd>
                                        {% if request.user.nickname == '' %}
                                            {{ request.user.username }}
                                        {% else %}
                                            {{ request.user.nickname }}
                                        {% endif %}
                                        <img class="down fr" src="{% static 'images/top_down.png' %}" alt=""/>
                                    </dd>
                                    <dt><img width="20" height="20"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}" alt=""/>
                                    </dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80"
                                                 src="{{ MEDIA_URL }}{{ request.user.image }}" alt=""/>
                                        </dt>
                                        <dd>
                                            <h2>
                                                {% if request.user.nickname == '' %}
                                                    {{ request.user.username }}
                                                {% else %}
                                                    {{ request.user.nickname }}
                                                {% endif %}
                                            </h2>
                                            <p>{{ request.user.email }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                    </div>
                                </div>
                            </div>
                            <div class="fr" style="padding-right: 2em">
                                <a style="color:white;" class="fr registerbtn" href={% url 'users:register' %}>注册</a>
                            </div>

                            <!-- 消息提示 -->
                            <a href="{% url 'users:my_messages' %}">
                                <div class="msg-num">&nbsp;消息数：<span
                                        id="MsgNum">{{ request.user.getUnreadNum }}</span>
                                </div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href={% url 'users:register' %}>注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                        {% endif %}
                    </div>
                </div>

                <!-- 搜索框 -->
                <div class="middle">
                    <div class="wp">
                        <a href="{% url "index" %}"><img class="fl" src="{% static 'images/logo.jpg' %}" alt=""/></a>
                        <div class="searchbox fr">
                            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                                <ul class="selectMenu" id="jsSelectMenu">
                                    <li data-value="course">公开课</li>
                                    <li data-value="org">课程机构</li>
                                    <li data-value="teacher">授课老师</li>
                                </ul>
                            </div>
                            <label for="search_keywords"></label>

                            {# 用户通过关键字搜索则保留搜索的字符和选项 #}
                            {% if request.path|slice:'14' == '/courses/list/' %}
                                <script>$('#jsSelectOption').attr('data-value', 'course').text('公开课')</script>
                                <input id="search_keywords" class="fl" type="text"
                                       value="{% ifnotequal search_keyword '' %}{{ search_keyword }}{% endifnotequal %}"
                                       placeholder="请输入搜索内容"/>

                            {% elif request.path|slice:'20' == '/orgs/teachers_list/' %}
                                <script>$('#jsSelectOption').attr('data-value', 'teacher').text('授课老师')</script>
                                <input id="search_keywords" class="fl" type="text"
                                       value="{% ifnotequal search_keyword '' %}{{ search_keyword }}{% endifnotequal %}"
                                       placeholder="请输入搜索内容"/>

                            {% elif request.path|slice:'11' == '/orgs/list/' %}
                                <script>$('#jsSelectOption').attr('data-value', 'org').text('课程机构')</script>
                                <input id="search_keywords" class="fl" type="text"
                                       value="{% ifnotequal search_keyword '' %}{{ search_keyword }}{% endifnotequal %}"
                                       placeholder="请输入搜索内容"/>

                            {% else %}
                                <input id="search_keywords" class="fl" type="text"
                                       value="" placeholder="请输入搜索内容"/>

                            {% endif %}

                            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"
                                 alt=""/>
                        </div>
                    </div>
                </div>

                <!-- 主导航栏 -->
                <nav>
                    <div class="nav">
                        <div class="wp">
                            {# 使用slice筛选器对路径切片，取出特征部分来判断在哪个板块 #}
                            <ul>
                                <li {% if request.path == '/' or request.path == '/index/' %}class="active"{% endif %}>
                                    <a href="{% url "index" %}">首页</a>
                                </li>
                                <li {% if request.path|slice:'8' == '/courses' %}class="active"{% endif %}>
                                    <a href="{% url 'courses:list' %}">
                                        公开课<img class="hot" src="{% static 'images/nav_hot.png' %}" alt="">
                                    </a>
                                </li>
                                <li {% if request.path|slice:'14' == '/orgs/teachers' %}class="active"{% endif %}>
                                    <a href="{% url 'orgs:list_teachers' %}">授课教师</a>
                                </li>
                                <li {% if request.path|slice:'10' == '/orgs/list' %}class="active"{% endif %}>
                                    <a href="{% url 'orgs:list' %}">授课机构</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

            </div>
        </header>
    </section>

    {% block nav %}
        <!-- 面包屑导航 -->
        <section>
            <div class="wp">
                <ul class="crumbs">
                    <li><a href="{% url "index" %}">首页</a>></li>
                    <li><a href="{% url "index" %}">导航1</a>></li>
                </ul>
            </div>
        </section>
    {% endblock %}

    <!-- 主要内容 -->
    {% block main_content %}
    {% endblock %}

    <!-- 脚注 -->
    <footer>
        <div class="footer">
            <div class="wp">
                <ul class="cont">
                    <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}" alt=""/></a></li>
                    <li class="code"><img src="{% static 'images/code.jpg' %}" alt=""/>
                        <p class="center">扫描关注微信</p></li>
                    <li class="third"><img class="fl" src="{% static 'images/tell.png' %}" alt=""/>
                        <p class="tell">123456789</p>
                        <p class="time">周一至周日 9:00-18:00</p></li>
                </ul>
            </div>
            <p class="line"></p>
            <div class="wp clear">
                <span class="fl">&copy; 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright &copy; 2016</span>
            </div>
        </div>
    </footer>

    <!-- 侧边按钮 -->
    <section>
        <ul class="sidebar">
            <li class="totop"></li>
        </ul>
    </section>
</body>

{% block external_js %}
{% endblock %}

</html>

templates/base-orgs.html
<!DOCTYPE html>
<html lang="zh">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}标题{% endblock %}</title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
        <script src="{% static 'js/selectUi.js' %}"></script>
        <script src="{% static 'js/deco-common.js' %}"></script>
        <script src="{% static 'js/unslider.js' %}"></script>
        <script src="{% static 'js/index.js' %}"></script>
        <script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
        <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
        <script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
        <script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>
    {% endblock %}
</head>
<body>
    <!-- header介绍 -->
    <section class="headerwrap headerwrap2">
        <header id="top">
            <div class="header2 header">
                <!-- 顶部水平栏 -->
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>123456789</b></p></div>
                        <!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                            <div class="personal">
                                <dl class="user fr">
                                    <dd>
                                        {% if request.user.nickname == '' %}
                                            {{ request.user.username }}
                                        {% else %}
                                            {{ request.user.nickname }}
                                        {% endif %}
                                        <img class="down fr" src="{% static 'images/top_down.png' %}" alt=""/>
                                    </dd>
                                    <dt><img width="20" height="20"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}" alt=""/>
                                    </dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80"
                                                 src="{{ MEDIA_URL }}{{ request.user.image }}" alt=""/>
                                        </dt>
                                        <dd>
                                            <h2>
                                                {% if request.user.nickname == '' %}
                                                    {{ request.user.username }}
                                                {% else %}
                                                    {{ request.user.nickname }}
                                                {% endif %}
                                            </h2>
                                            <p>{{ request.user.email }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                    </div>
                                </div>
                            </div>
                            <div class="fr" style="padding-right: 2em">
                                <a style="color:white;" class="fr registerbtn" href={% url 'users:register' %}>注册</a>
                            </div>

                            <!-- 消息提示 -->
                            <a href="{% url 'users:my_messages' %}">
                                <div class="msg-num">&nbsp;消息数：<span
                                        id="MsgNum">{{ request.user.getUnreadNum }}</span>
                                </div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href={% url 'users:register' %}>注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                        {% endif %}
                    </div>
                </div>

                <div class="middle companyheader" style="margin-top: 1em">
                    <div class="wp">
                        <!-- 主logo -->
                        {% block org_logo %}
                            <img class="fl" style="width: 112px; height: 103px" src="" alt=""/>
                        {% endblock %}
                        <div class="head fl">
                            <!-- 主标题 -->
                            {% block h1 %}
                                主标题
                                <h1>
                                    <img src="{% static 'images/authentication.png' %}" alt=""/>
                                    <img src="{% static 'images/gold.png' %}" alt=""/>
                                </h1>
                            {% endblock %}
                            <p class="fl">
                                <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                                <span class="precision company-credit" data-star-scope="5.0"></span>
                                <span class="key">5.0</span>
                            </p>
                        </div>
                        <div id="jsFavBtn" class="btn fr collectionbtn notlogin">
                            {% if has_fav %}已收藏{% else %}收藏{% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </section>

    <!-- 面包屑导航 -->
    <section>
        <div class="wp">
            <ul class="crumbs">
                {% block bread-nav %}
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'orgs:list' %}">课程机构</a>></li>
                    <li><a href="">机构首页</a></li>
                {% endblock %}
            </ul>
        </div>
    </section>

    <section>
        <div class="wp list personal_list comp">
            <!-- 左侧栏 -->
            <div class="left">
                <ul>
                    {% block active_item %}
                        <li class=""><a href="">机构首页</a></li>
                        <li class=""><a href="">机构课程</a></li>
                        <li class=""><a href="">机构介绍</a></li>
                        <li class=""><a href="">机构讲师</a></li>
                    {% endblock %}
                </ul>
            </div>

            <!-- 全部课程 -->
            {% block content-courses %}

            {% endblock %}

            <!-- 机构教师 -->
            {% block content-teachers %}

            {% endblock %}

            <!-- 机构介绍 -->
            {% block content-intro %}

            {% endblock %}
        </div>
    </section>

    <!-- 侧边按钮 -->
    <section>
        <ul class="sidebar">
            <li class="totop"><a href="#top"></a></li>
        </ul>
    </section>

    {% block external_js %}
        <script>
            $(function () {
                $('#jsFavBtn').on('click', function () {
                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "{% url 'operations:add_fav' %}",
                        dataType: "json",
                        data: {'fav_id': '{{ course_orgs.id }}', 'fav_type': 2},
                        async: true,
                        beforeSend: function (xhr) {
                            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                        },
                        success: function (data) {
                            if (data.status === 'fail') {
                                if (data.msg === '用户未登录') {
                                    window.location.href = "{% url 'users:login' %}";
                                } else {
                                    console.log(data.msg)
                                }

                            } else if (data.status === 'success') {
                                $('#jsFavBtn').text(data.msg)
                            }
                        },
                        error: function () {
                            console.log('error')
                        },
                    });
                });
            })
        </script>
    {% endblock %}
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'base-users.html' %}
{% load static %}

{% block title %}个人中心-我的收藏{% endblock %}
{% block crumb-nav %}
    <ul class="crumbs">
        <li><a href="{% url 'index' %}">首页</a>></li>
        <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
        <li>我的收藏</li>
    </ul>
{% endblock %}

{% block right_title %}我的收藏{% endblock %}

{% block right_tab %}
    <div class="head">
        <ul class="tab_header messagehead">
            <li><a href="{% url 'users:my_favourite' 'org' %}">课程机构</a></li>
            <li><a href="{% url 'users:my_favourite' 'teacher' %}">授课教师</a></li>
            <li class="active"><a href="{% url 'users:my_favourite' 'courses' %}">公开课程</a></li>
        </ul>
    </div>
{% endblock %}

{% block right_content %}
    {# 没有数据显示时调用父模板的显示内容 #}
    {% ifequal my_courses.count 0 %}
        {{ block.super }}
    {% else %}
        <div class="companycenter" style="width: 110%">
            <div class="group_list brief">
                {% for item in my_courses %}
                    <div class="module1_5 box">
                        <a href="{% url 'courses:course_detail' item.id %}">
                            <img width="214" height="190" class="scrollLoading"
                                 src="{{ MEDIA_URL }}{{ item.images }}" alt=""/>
                        </a>
                        <div class="des">
                            <a href="{% url 'courses:course_detail' item.id %}"><h2>{{ item.name }}</h2></a>
                            <span class="fl">课时：<i class="key">{{ item.study_times }}</i></span>
                            <span class="fr">学习人数：{{ item.students_num }}</span>
                        </div>
                        <div class="bottom">
                            <span class="fl">{{ item.organization.name }}</span>
                            <span class="delete-group fr jsDeleteFav_course" data-favid="{{ item.id }}"></span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endifequal %}
{% endblock %}

{% block end-js %}
    <script>
        $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'operations:add_fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function () {
                    Dml.fun.showTipsDialog({
                        title: '取消收藏',
                        h2: '取消收藏成功!',
                    });
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'base-users.html' %}
{% load static %}

{% block title %}个人中心-我的收藏{% endblock %}
{% block crumb-nav %}
    <ul class="crumbs">
        <li><a href="{% url 'index' %}">首页</a>></li>
        <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
        <li>我的收藏</li>
    </ul>
{% endblock %}

{% block right_title %}我的收藏{% endblock %}

{% block right_tab %}
    <div class="head">
        <ul class="tab_header messagehead">
            <li class="active"><a href="{% url 'users:my_favourite' 'org' %}">课程机构</a></li>
            <li><a href="{% url 'users:my_favourite' 'teacher' %}">授课教师</a></li>
            <li><a href="{% url 'users:my_favourite' 'courses' %}">公开课程</a></li>
        </ul>
    </div>
{% endblock %}

{% block right_content %}
    {# 没有数据显示时调用父模板的显示内容 #}
    {% ifequal my_orgs.count 0 %}
        {{ block.super }}
    {% else %}
        {% for item in my_orgs %}
            <div class="messages messagelist butler_list company company-fav-box">
                <dl class="des fr">
                    <dt>
                        <a href="{% url 'orgs:home' item.id %}">
                            <img width="160" height="90" src="{{ MEDIA_URL }}{{ item.images }}" alt=""/>
                        </a>
                    </dt>
                    <dd>
                        <h1><a href="{% url 'orgs:home' item.id %}">{{ item.name }}</a></h1>
                        <div class="pic fl" style="width:auto;">
                            <img src="{% static 'images/authentication.png' %}" alt=""/>
                            <img src="{% static 'images/gold.png' %}" alt=""/>
                        </div>
                        <span class="c8 clear">{{ item.city.name }}</span>
                    </dd>
                    <div class="delete jsDeleteFav_org" data-favid="{{ item.id }}"></div>
                </dl>
            </div>
        {% endfor %}
    {% endifequal %}
{% endblock %}

{% block end-js %}
    <script>
        $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'operations:add_fav' %}",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function () {
                    Dml.fun.showTipsDialog({
                        title: '取消收藏',
                        h2: '取消收藏成功!',
                    });
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}